import { ProfileId, profiles } from "@/lib/profiles";

export interface BlogPost {
  slug: string;
  title: string;
  metaDescription: string;
  excerpt: string;
  date: string;
  relatedProfile?: ProfileId;
  relatedProfiles?: [ProfileId, ProfileId];
  matchType?: "ideal" | "complementaire";
  content: string[];
}

export const posts: BlogPost[] = [
  {
    slug: "profil-ancrage-familial",
    title: "Vous êtes un profil Ancrage Familial ? Voici ce qui compte vraiment pour vous en couple",
    metaDescription: "Découvrez ce qui définit le profil de compatibilité Ancrage Familial et ce que cette vision du couple implique dans une relation durable.",
    excerpt: "Pour ce profil, le mariage se construit avant tout autour de la famille et de la stabilité.",
    date: "2026-08-25",
    relatedProfile: "ancrage_familial",
    content: [
      "Si le test de compatibilité Nawa vous a attribué le profil Ancrage Familial, ce n'est pas un hasard : chacune de vos réponses a révélé une même priorité, celle de bâtir un foyer stable, chaleureux et durable.",
      "Pour vous, le mariage n'est pas qu'une union entre deux personnes. C'est la fondation d'une famille, avec tout ce que cela suppose de transmission, de repères et de continuité. Vous imaginez naturellement les dimanches en famille, les enfants qui grandissent dans un cadre sécurisant, et une maison qui reste le point d'ancrage de tous.",
      "Ce n'est pas un manque d'ambition personnelle ou de goût pour la nouveauté. C'est une hiérarchie de priorités claire : la solidité du foyer passe avant le reste.",
      "Ce qui compte vraiment pour vous en couple",
      "Trois éléments reviennent systématiquement chez les profils Ancrage Familial : la fiabilité de l'autre sur la durée, la capacité à créer un environnement chaleureux au quotidien, et un rapport apaisé à la famille élargie. Un partenaire imprévisible, ou qui place son indépendance bien au-dessus de la vie de famille, créera chez vous une forme d'insécurité, même si l'attirance est réelle au départ.",
      "Avec qui êtes-vous le plus compatible ?",
      "Le profil qui s'accorde le mieux avec le vôtre est le Complice du Quotidien : cette personne partage votre attachement aux petits moments simples et à la chaleur du foyer, sans pour autant reproduire exactement votre façon de voir les choses — ce qui équilibre la relation plutôt que de la dupliquer. Le Cœur Spirituel est également un bon complément : vos deux visions du mariage reposent sur un socle de valeurs et de stabilité proche.",
      "Faites le test de compatibilité Nawa pour découvrir votre profil complet et les célibataires sérieux qui partagent votre vision du couple.",
    ],
  },
  {
    slug: "profil-aventurier-engage",
    title: "Aventurier Engagé en amour : comment concilier liberté et engagement",
    metaDescription: "Le profil Aventurier Engagé veut un mariage qui n'exclut pas la découverte. Comprendre cette vision du couple et les partenaires les plus compatibles.",
    excerpt: "Ce profil veut un mariage qui laisse de la place à la découverte et à l'évolution personnelle.",
    date: "2026-08-27",
    relatedProfile: "aventurier_engage",
    content: [
      "L'Aventurier Engagé est souvent mal compris : on suppose à tort que vouloir du mouvement et de la découverte dans sa vie signifie fuir l'engagement. C'est l'inverse. Ce profil veut un mariage solide, mais refuse qu'il devienne synonyme de routine figée.",
      "Ce qui vous anime, c'est l'idée qu'un couple peut grandir ensemble sans s'enfermer : découvrir de nouveaux endroits, apprendre, évoluer professionnellement ou personnellement, tout en construisant une relation stable. Le mariage, pour vous, n'est pas un point d'arrêt mais un projet vivant.",
      "La tension à anticiper",
      "Le principal défi de ce profil est de trouver un partenaire qui ne confond pas votre besoin de mouvement avec un manque d'investissement. Un partenaire trop attaché à la routine ou à l'immobilisme peut vite se sentir délaissé, alors que vous, de votre côté, vous sentirez étouffé par trop de rigidité.",
      "Avec qui êtes-vous le plus compatible ?",
      "Le Bâtisseur de Projet est votre match idéal : vous partagez tous les deux une orientation vers l'avenir et la construction, lui à travers des objectifs concrets, vous à travers l'exploration — une combinaison qui avance dans la même direction sans se marcher dessus. Le Complice du Quotidien fonctionne aussi très bien en complément : sa légèreté équilibre votre besoin de nouveauté par une capacité à profiter du moment présent, où que vous soyez.",
      "Faites le test de compatibilité Nawa pour découvrir votre profil complet et les célibataires sérieux qui partagent votre vision du couple.",
    ],
  },
  {
    slug: "profil-batisseur-de-projet",
    title: "Bâtisseur de Projet : quand le couple devient une équipe",
    metaDescription: "Le profil Bâtisseur de Projet envisage le couple comme une équipe tournée vers des objectifs communs. Découvrez ce que cela implique en compatibilité.",
    excerpt: "Pour ce profil, le couple fonctionne comme une équipe tournée vers des objectifs communs.",
    date: "2026-08-29",
    relatedProfile: "batisseur_projet",
    content: [
      "Chez le Bâtisseur de Projet, l'amour ne suffit pas à lui seul : encore faut-il qu'il se traduise en direction commune. Ce profil envisage naturellement le couple comme une équipe, avec des objectifs partagés — carrière, projets, stabilité financière, ambitions de vie.",
      "Ce n'est pas une vision froide ou calculatrice du mariage. C'est une façon de sécuriser la relation par des preuves concrètes d'engagement : construire ensemble, avancer ensemble, se projeter ensemble sur des horizons précis plutôt que sur des promesses vagues.",
      "Ce que ce profil recherche vraiment",
      "Un partenaire aussi investi que vous dans la construction d'un avenir concret, capable de fixer des objectifs communs et de s'y tenir. Un manque d'ambition partagée, ou une approche trop attentiste de la vie à deux, peut rapidement créer chez vous un sentiment de déséquilibre, même si l'entente émotionnelle est bonne par ailleurs.",
      "Avec qui êtes-vous le plus compatible ?",
      "L'Aventurier Engagé est votre match idéal : son goût pour le mouvement et l'évolution personnelle rejoint votre orientation vers l'avenir, chacun nourrissant le projet commun à sa façon. Le Protecteur Discret complète bien votre profil aussi : sa loyauté discrète et sa prudence apportent un contrepoids stabilisant à votre énergie tournée vers l'action.",
      "Faites le test de compatibilité Nawa pour découvrir votre profil complet et les célibataires sérieux qui partagent votre vision du couple.",
    ],
  },
  {
    slug: "profil-coeur-spirituel",
    title: "Cœur Spirituel : construire un couple autour de ses valeurs profondes",
    metaDescription: "Le profil Cœur Spirituel place ses valeurs et sa spiritualité au centre de sa vision du mariage. Comprendre ce profil et ses meilleures compatibilités.",
    excerpt: "Ce profil place ses valeurs profondes au centre de sa vision du mariage.",
    date: "2026-08-31",
    relatedProfile: "coeur_spirituel",
    content: [
      "Pour le Cœur Spirituel, un mariage ne se juge pas seulement à la qualité de la relation au quotidien, mais à la solidité du socle sur lequel elle repose. Vos valeurs, qu'elles soient religieuses, spirituelles ou simplement des principes de vie profondément ancrés, sont au centre de votre vision du couple.",
      "Vous ne cherchez pas nécessairement un partenaire identique à vous sur tous les plans, mais quelqu'un capable de comprendre, respecter et idéalement partager ce socle. Sans cet alignement, même une relation par ailleurs harmonieuse peut manquer de profondeur à vos yeux.",
      "Ce qui fait la différence pour vous",
      "La sincérité prime sur beaucoup d'autres critères. Un partenaire dont les valeurs affichées ne correspondent pas aux actes du quotidien créera rapidement une distance, même invisible de l'extérieur. À l'inverse, un désaccord de forme (rythme de vie, tempérament) pèse peu face à un vrai alignement de fond.",
      "Avec qui êtes-vous le plus compatible ?",
      "L'Ancrage Familial est votre match idéal : sa recherche de stabilité et de transmission rejoint directement votre besoin d'un socle solide et durable. Le Protecteur Discret est également un excellent complément : sa loyauté et sa discrétion s'accordent bien avec votre approche posée et sincère de la relation.",
      "Faites le test de compatibilité Nawa pour découvrir votre profil complet et les célibataires sérieux qui partagent votre vision du couple.",
    ],
  },
  {
    slug: "profil-complice-du-quotidien",
    title: "Complice du Quotidien : et si le bonheur se cachait dans les petits moments",
    metaDescription: "Le profil Complice du Quotidien vit le couple à travers les petits moments partagés. Découvrez cette vision du mariage et ses compatibilités idéales.",
    excerpt: "Pour ce profil, un mariage réussi se vit dans les petits moments du quotidien.",
    date: "2026-09-02",
    relatedProfile: "complice_quotidien",
    content: [
      "Le Complice du Quotidien ne mesure pas la réussite d'un couple à de grands accomplissements, mais à l'accumulation de petits moments : un fou rire partagé, une habitude tendre, une présence rassurante chaque jour. C'est une vision simple, mais loin d'être superficielle.",
      "Ce profil sait qu'un mariage se vit à 95% dans le quotidien, pas dans les grandes occasions. Ce qui compte, c'est la qualité de la complicité installée jour après jour : l'humour partagé, la facilité à être soi-même, la légèreté qui désamorce les tensions avant qu'elles ne s'installent.",
      "Ce à quoi vous êtes le plus sensible",
      "La distance émotionnelle est ce qui vous pèse le plus dans une relation, bien plus qu'un désaccord ponctuel. Un partenaire trop sérieux en permanence, ou incapable de savourer les moments simples, peut vous donner l'impression d'un couple qui fonctionne sans jamais vraiment se retrouver.",
      "Avec qui êtes-vous le plus compatible ?",
      "L'Ancrage Familial est votre match idéal : son attachement au foyer et à la chaleur familiale rejoint parfaitement votre besoin de complicité quotidienne. L'Aventurier Engagé fonctionne bien en complément : votre légèreté équilibre son besoin de mouvement, en lui rappelant que le bonheur se trouve aussi dans l'instant présent.",
      "Faites le test de compatibilité Nawa pour découvrir votre profil complet et les célibataires sérieux qui partagent votre vision du couple.",
    ],
  },
  {
    slug: "profil-protecteur-discret",
    title: "Protecteur Discret : loyauté et discrétion, les piliers d'un amour solide",
    metaDescription: "Le profil Protecteur Discret privilégie la loyauté et la sécurité affective. Comprendre cette vision du couple et ses meilleures compatibilités.",
    excerpt: "Ce profil privilégie la loyauté, la sécurité affective et la discrétion en couple.",
    date: "2026-09-04",
    relatedProfile: "protecteur_discret",
    content: [
      "Le Protecteur Discret ne cherche ni l'agitation ni la mise en avant. Ce qui compte pour vous, c'est la solidité tranquille d'une relation où la confiance n'est jamais remise en question — construite loin du bruit, sur la durée.",
      "Vous privilégiez naturellement la loyauté et la sécurité affective à l'intensité ou à la nouveauté permanente. Un couple, pour vous, doit avant tout être un espace sûr, où l'on peut baisser la garde sans crainte d'être trahi ou exposé inutilement.",
      "Ce qui compte vraiment pour vous en couple",
      "La discrétion n'est pas un manque d'affection, c'est une façon de protéger ce qui est précieux. Un partenaire trop imprévisible, ou qui expose facilement la vie du couple à l'extérieur, créera chez vous un inconfort réel, même sans conflit apparent.",
      "Avec qui êtes-vous le plus compatible ?",
      "Le Cœur Spirituel est votre match idéal : sa sincérité et son attachement à des valeurs profondes rejoignent directement votre besoin de confiance durable. Le Bâtisseur de Projet est un bon complément également : sa détermination bénéficie de votre stabilité, tandis que vous trouvez en lui un cadre concret et rassurant.",
      "Faites le test de compatibilité Nawa pour découvrir votre profil complet et les célibataires sérieux qui partagent votre vision du couple.",
    ],
  },
  {
    slug: "paire-ancrage-familial-complice-quotidien",
    title: "Ancrage Familial x Complice du Quotidien : le duo qui construit un foyer solide",
    metaDescription: "Pourquoi les profils Ancrage Familial et Complice du Quotidien forment l'une des paires de compatibilité les plus solides sur Nawa.",
    excerpt: "Deux profils qui placent la chaleur du foyer et les petits moments au centre du couple.",
    date: "2026-09-06",
    relatedProfiles: ["ancrage_familial", "complice_quotidien"],
    matchType: "ideal",
    content: [
      "Sur Nawa, cette paire fait partie de celles qui affichent le score de compatibilité le plus élevé — et ce n'est pas un hasard statistique. Ancrage Familial et Complice du Quotidien partagent une même conviction : le mariage se vit et se construit dans les gestes simples du quotidien, pas dans les grandes déclarations.",
      "Ce qui les rapproche",
      "L'Ancrage Familial apporte la structure et la vision à long terme d'un foyer stable. Le Complice du Quotidien apporte la légèreté et la capacité à savourer chaque moment, sans laisser la routine s'installer. L'un construit le cadre, l'autre le remplit de vie — la combinaison fonctionne parce qu'aucun des deux n'impose une vision opposée à l'autre.",
      "Le point de vigilance",
      "Le risque, dans cette paire, est que l'Ancrage Familial pousse trop vite vers de grandes étapes (installation, enfants, projets familiaux) avant que le Complice du Quotidien n'ait eu le temps de construire la complicité qui le rassure. Prendre le temps de la légèreté avant de formaliser évite cette friction.",
      "Faites le test de compatibilité Nawa pour découvrir votre profil et savoir si vous formez, vous aussi, une paire à fort potentiel.",
    ],
  },
  {
    slug: "paire-ancrage-familial-coeur-spirituel",
    title: "Ancrage Familial x Cœur Spirituel : un socle de valeurs communes",
    metaDescription: "La paire Ancrage Familial et Cœur Spirituel repose sur un socle de valeurs partagées. Découvrez pourquoi cette compatibilité fonctionne bien.",
    excerpt: "Deux visions du couple ancrées dans la stabilité et des valeurs profondes.",
    date: "2026-09-08",
    relatedProfiles: ["ancrage_familial", "coeur_spirituel"],
    matchType: "ideal",
    content: [
      "Cette paire repose sur un point commun fort : les deux profils cherchent un mariage bâti sur des fondations solides, qu'elles soient familiales ou spirituelles. C'est cette convergence de fond qui fait le succès de cette compatibilité.",
      "Ce qui les rapproche",
      "L'Ancrage Familial veut un foyer stable et transmissible. Le Cœur Spirituel veut un couple aligné sur des valeurs profondes. Dans les deux cas, l'engagement se juge sur la durée et la cohérence, pas sur l'intensité du moment. Ensemble, ils construisent une relation où chacun sait ce que l'autre défend vraiment.",
      "Le point de vigilance",
      "Le Cœur Spirituel peut avoir besoin de discussions de fond régulières sur le sens du couple, là où l'Ancrage Familial se satisfait parfois de la stabilité concrète sans forcément la nommer. Prendre le temps de verbaliser les valeurs communes, plutôt que de les supposer acquises, renforce cette paire.",
      "Faites le test de compatibilité Nawa pour découvrir votre profil et savoir si vous formez, vous aussi, une paire à fort potentiel.",
    ],
  },
  {
    slug: "paire-aventurier-engage-batisseur-projet",
    title: "Aventurier Engagé x Bâtisseur de Projet : ambition et liberté main dans la main",
    metaDescription: "Découvrez pourquoi Aventurier Engagé et Bâtisseur de Projet forment l'une des paires de compatibilité les plus dynamiques sur Nawa.",
    excerpt: "Deux profils tournés vers l'avenir, chacun à sa façon.",
    date: "2026-09-10",
    relatedProfiles: ["aventurier_engage", "batisseur_projet"],
    matchType: "ideal",
    content: [
      "Cette paire fonctionne parce qu'elle réunit deux moteurs différents autour d'une même direction : avancer. L'Aventurier Engagé avance par l'exploration et l'évolution personnelle, le Bâtisseur de Projet avance par la structuration et les objectifs concrets.",
      "Ce qui les rapproche",
      "Aucun des deux profils ne se satisfait de l'immobilisme. Cette énergie commune évite l'écueil classique où l'un des deux se sent freiné par l'autre. Le Bâtisseur de Projet donne un cadre aux envies de l'Aventurier Engagé, qui lui-même empêche le Bâtisseur de s'enfermer dans une routine trop rigide.",
      "Le point de vigilance",
      "Le risque est que chacun avance sur son propre projet sans suffisamment se synchroniser. Cette paire gagne à définir régulièrement des objectifs communs explicites, pour que l'énergie des deux profils converge plutôt que de simplement coexister.",
      "Faites le test de compatibilité Nawa pour découvrir votre profil et savoir si vous formez, vous aussi, une paire à fort potentiel.",
    ],
  },
  {
    slug: "paire-coeur-spirituel-protecteur-discret",
    title: "Cœur Spirituel x Protecteur Discret : loyauté et profondeur",
    metaDescription: "La paire Cœur Spirituel et Protecteur Discret associe sincérité des valeurs et loyauté discrète. Découvrez cette compatibilité en détail.",
    excerpt: "Une paire fondée sur la confiance durable et l'alignement de valeurs.",
    date: "2026-09-12",
    relatedProfiles: ["coeur_spirituel", "protecteur_discret"],
    matchType: "ideal",
    content: [
      "Cette paire se distingue par une qualité rare : une confiance qui s'installe vite et dure longtemps. Le Cœur Spirituel cherche la sincérité et l'alignement de valeurs ; le Protecteur Discret cherche la loyauté et la sécurité affective. Les deux quêtes se rejoignent naturellement.",
      "Ce qui les rapproche",
      "Ni l'un ni l'autre ne fonctionne dans l'agitation ou la démonstration. Cette paire construit une relation posée, où l'engagement se prouve par la constance plutôt que par les grands gestes. Le Protecteur Discret sécurise la relation, le Cœur Spirituel lui donne du sens.",
      "Le point de vigilance",
      "Les deux profils étant naturellement réservés, cette paire peut manquer d'occasions de vraiment exprimer ce qu'elle ressent. Se forcer à verbaliser régulièrement l'attachement, plutôt que de le considérer comme implicite, évite que la relation ne devienne trop silencieuse.",
      "Faites le test de compatibilité Nawa pour découvrir votre profil et savoir si vous formez, vous aussi, une paire à fort potentiel.",
    ],
  },
  {
    slug: "paire-aventurier-engage-complice-quotidien",
    title: "Aventurier Engagé x Complice du Quotidien : l'équilibre entre mouvement et légèreté",
    metaDescription: "Aventurier Engagé et Complice du Quotidien forment une paire complémentaire sur Nawa. Découvrez ce qui les rend compatibles malgré leurs différences.",
    excerpt: "Un profil qui cherche le mouvement, un autre qui savoure l'instant présent.",
    date: "2026-09-14",
    relatedProfiles: ["aventurier_engage", "complice_quotidien"],
    matchType: "complementaire",
    content: [
      "Contrairement aux paires de match idéal, cette compatibilité repose sur la complémentarité plutôt que sur la ressemblance. L'Aventurier Engagé a besoin de mouvement et de nouveauté ; le Complice du Quotidien sait savourer l'instant présent, où qu'il se trouve. C'est cet équilibre qui fait la force de cette paire.",
      "Ce qui les rapproche",
      "Le Complice du Quotidien empêche l'Aventurier Engagé de courir après la nouveauté sans jamais profiter du moment présent. En retour, l'Aventurier Engagé sort le Complice du Quotidien de sa zone de confort, sans jamais le brusquer.",
      "Le point de vigilance",
      "Le Complice du Quotidien peut se sentir déstabilisé si le rythme de changement est trop rapide ; l'Aventurier Engagé peut se sentir freiné si tout doit toujours rester familier. Trouver un rythme de nouveauté qui convient aux deux est la clé de cette paire.",
      "Faites le test de compatibilité Nawa pour découvrir votre profil et savoir si vous formez, vous aussi, une paire à fort potentiel.",
    ],
  },
  {
    slug: "paire-batisseur-projet-protecteur-discret",
    title: "Bâtisseur de Projet x Protecteur Discret : l'ambition portée par la stabilité",
    metaDescription: "Bâtisseur de Projet et Protecteur Discret forment une paire complémentaire sur Nawa, entre détermination et prudence. Découvrez cette compatibilité.",
    excerpt: "Un profil tourné vers l'action, un autre vers la stabilité — un bon équilibre.",
    date: "2026-09-16",
    relatedProfiles: ["batisseur_projet", "protecteur_discret"],
    matchType: "complementaire",
    content: [
      "Cette paire associe deux forces différentes mais compatibles : la détermination du Bâtisseur de Projet et la prudence loyale du Protecteur Discret. Là où l'un pousse à avancer, l'autre veille à ce que les fondations restent solides.",
      "Ce qui les rapproche",
      "Le Bâtisseur de Projet apporte une direction claire et des objectifs concrets. Le Protecteur Discret apporte la stabilité affective et la constance nécessaires pour que ces projets tiennent dans la durée. L'un sans l'autre risquerait soit de stagner, soit d'avancer trop vite sans base solide.",
      "Le point de vigilance",
      "Le Bâtisseur de Projet peut parfois trouver le Protecteur Discret trop prudent face à une opportunité ; le Protecteur Discret peut trouver le rythme du Bâtisseur trop rapide. Prendre le temps d'expliciter les décisions importantes, plutôt que d'avancer dans l'urgence, renforce la confiance entre les deux.",
      "Faites le test de compatibilité Nawa pour découvrir votre profil et savoir si vous formez, vous aussi, une paire à fort potentiel.",
    ],
  },
];

export function getPostBySlug(slug: string): BlogPost | undefined {
  return posts.find((p) => p.slug === slug);
}
